### ISSUE TITLE
Status of macOS support

### ISSUE THREAD

**Issue by mack-at-pieces** [hlwhl/webview_cef#10]
Hi there - On the plugin listing on pub.dev it claims this plugin has support for macOS, but it seems this is not built out yet. What's the status of this?

Thanks!

**Comment by hlwhl** [comment]
Sorry, macos support is still in developing, currently i'm focusing on macos support.

**Comment by mack-at-pieces** [comment]
@hlwhl okay great! do you have any idea on a timeline for when that may be available or at least in a beta state?

**Comment by hlwhl** [comment]
I'll try my best for dropping macos support next month😊

**Comment by hlwhl** [comment]
![image](https://user-images.githubusercontent.com/7610615/185367742-e2345d48-d629-47fd-88ee-9f4761c65e29.png)
will drop mac support soon👏

**Comment by inf0rmatix** [comment]
this should be closed then?

**Comment by hlwhl** [comment]
> this should be closed then?

@inf0rmatix Yeah, macOS support dropped via #14 .
