### ISSUE TITLE
windows鼠标滚动不流畅；关于prebuilt package分发的建议

### ISSUE THREAD

**Issue by Chihiro23333** [hlwhl/webview_cef#102]
1、打印日志发现onPointerSignal:监听中的signal.scrollDelta.dy.round()每次都在80左右，导致每次滑动距离较远，显示效果上看就是飞速的下滑，慢点滑就是一顿一顿的感觉，整个效果没有windows自带浏览器丝滑。
2、关于prebuilt package分发(windows)，可否把prebuilt package做成dll形式，运行时将dll放在对应的文件夹即可完整运行。然后提供一个api检测是否当前是否存在prebuilt package，提供相关信息用于前端展示。此建议的初衷是保证应用安装包的大小，并且在没有prebuilt package的应用也能正常使用，对于使用到了prebuilt package的界面，检测并提示让使用者自行下载对应的prebuilt package并存放在对应文件夹即可使用（对于windows开发不是很专业，仅仅是建议，仅做参考(笑哭)）。

**Comment by SinyimZhi** [comment]
@Chihiro23333 
1.目前开发工作量还是比较偏向于功能实现，细节的体验优化部分可能照顾不太到，滚动距离可以在以下函数处尝试调整
`void WebviewHandler::sendScrollEvent(int browserId, int x, int y, int deltaX, int deltaY)`
2.事实上 prebuilt package就是cef的编译产物，且大多数存储空间占用都是dll和lib，详见 libcef.dll、libcef_dll_wrapper.lib。这些dll、lib基本都是cef引擎运行所必须的。可忽略的资源文件size占比实在不值一提。我们提供的prebuilt package是包括了debug和release版的编译产物。方便开发人员调试，应用安装包构建并不需要全部包含，甚至不需要自己去挑选寻找。具体可以参考一些flutter windows编译产物制作安装包的教程，运行所需要的产物在编译后已经被拷贝在exe文件生成的位置了。

**Comment by Chihiro23333** [comment]
了解了，非常感谢！
