### ISSUE TITLE
调用dispose方法后闪退

### ISSUE THREAD

**Issue by Chihiro23333** [hlwhl/webview_cef#104]
平台：windows11-23H2
新开一个页面展示webview，退出界面时调用dispose方法，界面退出后应用会未响应，然后闪退。不调用dispose方法则无问题，此问题必现。关键代码如下：
  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

**Comment by SinyimZhi** [comment]
同一个问题，关联 #96

**Comment by SinyimZhi** [comment]
Hi, every one. I've merged multi instance and multi window support branch to main. There is a lot of problems might have been resloved. Could you guys help us to verify what we did success and what new problem brought in? @Chihiro23333
