### ISSUE TITLE
macOS14.3 & Xcode15.2 run example report Undefined symbols

### ISSUE THREAD

**Issue by luoguilin** [hlwhl/webview_cef#106]
ld: Undefined symbols:
  CefShutdown(), referenced from:
      webview_cef::HandleMethodCall(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, webview_value*, std::__1::function<void (int, webview_value*)>) in cef_bridge.o
  CefURIEncode(CefStringBase<CefStringTraitsUTF16> const&, bool), referenced from:
      (anonymous namespace)::GetDataURI(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in cef_bridge.o
  CefInitialize(CefMainArgs const&, CefStructBase<CefSettingsTraits> const&, scoped_refptr<CefApp>, void*), referenced from:
      webview_cef::startCEF() in cef_bridge.o
  CefCurrentlyOn(cef_thread_id_t), referenced from:
      WebviewApp::OnContextInitialized() in cef_bridge.o
      WebviewHandler::OnAfterCreated(scoped_refptr<CefBrowser>) in cef_bridge.o
      WebviewHandler::DoClose(scoped_refptr<CefBrowser>) in cef_bridge.o
      WebviewHandler::OnBeforeClose(scoped_refptr<CefBrowser>) in cef_bridge.o
      WebviewHandler::OnLoadError(scoped_refptr<CefBrowser>, scoped_refptr<CefFrame>, cef_errorcode_t, CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
      WebviewHandler::CloseAllBrowsers(bool) in cef_bridge.o
      WebviewHandler::GetViewRect(scoped_refptr<CefBrowser>, CefRect&) in cef_bridge.o
      ...
  CefBase64Encode(void const*, unsigned long), referenced from:
      (anonymous namespace)::GetDataURI(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in cef_bridge.o
  CefExecuteProcess(CefMainArgs const&, scoped_refptr<CefApp>, void*), referenced from:
      webview_cef::initCEFProcesses() in cef_bridge.o
  CefQuitMessageLoop(), referenced from:
      WebviewHandler::OnBeforeClose(scoped_refptr<CefBrowser>) in cef_bridge.o
  CefDoMessageLoopWork(), referenced from:
      webview_cef::doMessageLoopWork() in cef_bridge.o
  CefRegisterExtension(CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&, scoped_refptr<CefV8Handler>), referenced from:
      WebviewApp::OnWebKitInitialized() in cef_bridge.o
  CefV8Value::CreateBool(bool), referenced from:
      CefJSBridge::ExecuteJSCallbackFunc(int, bool, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
  CefV8Value::CreateString(CefStringBase<CefStringTraitsUTF16> const&), referenced from:
      CefJSBridge::ExecuteJSCallbackFunc(int, bool, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
  CefV8Value::CreateInt(int), referenced from:
      CefJSHandler::Execute(CefStringBase<CefStringTraitsUTF16> const&, scoped_refptr<CefV8Value>, std::__1::vector<scoped_refptr<CefV8Value>, std::__1::allocator<scoped_refptr<CefV8Value>>> const&, scoped_refptr<CefV8Value>&, CefStringBase<CefStringTraitsUTF16>&) in cef_bridge.o
  CefV8Context::GetCurrentContext(), referenced from:
      CefJSBridge::CallCppFunction(CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&, scoped_refptr<CefV8Value>, scoped_refptr<CefV8Value>) in cef_bridge.o
      CefJSBridge::StartRequest(int, CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
      CefJSBridge::EvaluateCallback(CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
  CefBrowserHost::CreateBrowser(CefWindowInfo const&, scoped_refptr<CefClient>, CefStringBase<CefStringTraitsUTF16> const&, CefStructBase<CefBrowserSettingsTraits> const&, scoped_refptr<CefDictionaryValue>, scoped_refptr<CefRequestContext>), referenced from:
      WebviewApp::OnContextInitialized() in cef_bridge.o
  CefCommandLine::GetGlobalCommandLine(), referenced from:
      WebviewHandler::IsChromeRuntimeEnabled() in cef_bridge.o
  CefCookieManager::GetGlobalManager(scoped_refptr<CefCompletionCallback>), referenced from:
      WebviewHandler::setCookie(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in cef_bridge.o
      WebviewHandler::deleteCookie(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in cef_bridge.o
      WebviewHandler::visitAllCookies(std::__1::function<void (std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>>>>)>) in cef_bridge.o
      WebviewHandler::visitUrlCookies(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool const&, std::__1::function<void (std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>>>>>>)>) in cef_bridge.o
  CefProcessMessage::Create(CefStringBase<CefStringTraitsUTF16> const&), referenced from:
      WebviewApp::OnFocusedNodeChanged(scoped_refptr<CefBrowser>, scoped_refptr<CefFrame>, scoped_refptr<CefDOMNode>) in cef_bridge.o
      WebviewHandler::sendJavaScriptChannelCallBack(bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) in cef_bridge.o
      CefJSBridge::CallCppFunction(CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&, scoped_refptr<CefV8Value>, scoped_refptr<CefV8Value>) in cef_bridge.o
      CefJSBridge::StartRequest(int, CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
      CefJSBridge::EvaluateCallback(CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
  CefScopedLibraryLoader::Load(bool), referenced from:
      CefScopedLibraryLoader::LoadInMain() in cef_bridge.o
  CefScopedLibraryLoader::CefScopedLibraryLoader(), referenced from:
      webview_cef::initCEFProcesses() in cef_bridge.o
  CefScopedLibraryLoader::~CefScopedLibraryLoader(), referenced from:
      webview_cef::initCEFProcesses() in cef_bridge.o
      webview_cef::initCEFProcesses() in cef_bridge.o
  cef::logging::LogMessage::LogMessage(char const*, int, int), referenced from:
      WebviewApp::OnContextInitialized() in cef_bridge.o
      scoped_refptr<CefJSHandler>::operator->() const in cef_bridge.o
      scoped_refptr<CefDOMNode>::operator->() const in cef_bridge.o
      scoped_refptr<CefProcessMessage>::operator->() const in cef_bridge.o
      scoped_refptr<CefListValue>::operator->() const in cef_bridge.o
      scoped_refptr<CefFrame>::operator->() const in cef_bridge.o
      WebviewHandler::WebviewHandler() in cef_bridge.o
      ...
  cef::logging::LogMessage::~LogMessage(), referenced from:
      WebviewApp::OnContextInitialized() in cef_bridge.o
      WebviewApp::OnContextInitialized() in cef_bridge.o
      scoped_refptr<CefJSHandler>::operator->() const in cef_bridge.o
      scoped_refptr<CefJSHandler>::operator->() const in cef_bridge.o
      scoped_refptr<CefDOMNode>::operator->() const in cef_bridge.o
      scoped_refptr<CefDOMNode>::operator->() const in cef_bridge.o
      scoped_refptr<CefProcessMessage>::operator->() const in cef_bridge.o
      scoped_refptr<CefProcessMessage>::operator->() const in cef_bridge.o
      ...
  _cef_string_ascii_to_utf16, referenced from:
      CefStringTraitsUTF16::from_ascii(char const*, unsigned long, _cef_string_utf16_t*) in cef_bridge.o
  _cef_string_utf16_clear, referenced from:
      CefWindowInfoTraits::clear(_cef_window_info_t*) in cef_bridge.o
      CefStringTraitsUTF16::clear(_cef_string_utf16_t*) in cef_bridge.o
      CefBrowserSettingsTraits::clear(_cef_browser_settings_t*) in cef_bridge.o
      CefBrowserSettingsTraits::clear(_cef_browser_settings_t*) in cef_bridge.o
      CefBrowserSettingsTraits::clear(_cef_browser_settings_t*) in cef_bridge.o
      CefBrowserSettingsTraits::clear(_cef_browser_settings_t*) in cef_bridge.o
      CefBrowserSettingsTraits::clear(_cef_browser_settings_t*) in cef_bridge.o
      CefBrowserSettingsTraits::clear(_cef_browser_settings_t*) in cef_bridge.o
      CefBrowserSettingsTraits::clear(_cef_browser_settings_t*) in cef_bridge.o
      CefBrowserSettingsTraits::clear(_cef_browser_settings_t*) in cef_bridge.o
      ...
  _cef_string_utf16_cmp, referenced from:
      CefStringTraitsUTF16::compare(_cef_string_utf16_t const*, _cef_string_utf16_t const*) in cef_bridge.o
  _cef_string_utf16_set, referenced from:
      CefStringTraitsUTF16::set(unsigned short const*, unsigned long, _cef_string_utf16_t*, int) in cef_bridge.o
      CefCookieTraits::set(_cef_cookie_t const*, _cef_cookie_t*, bool) in cef_bridge.o
      CefCookieTraits::set(_cef_cookie_t const*, _cef_cookie_t*, bool) in cef_bridge.o
      CefCookieTraits::set(_cef_cookie_t const*, _cef_cookie_t*, bool) in cef_bridge.o
      CefCookieTraits::set(_cef_cookie_t const*, _cef_cookie_t*, bool) in cef_bridge.o
      CefStringTraitsUTF16::from_string16(char16_t const*, unsigned long, _cef_string_utf16_t*) in cef_bridge.o
  _cef_string_utf16_to_utf8, referenced from:
      CefStringTraitsUTF16::to_string(_cef_string_utf16_t const*) in cef_bridge.o
  _cef_string_utf8_clear, referenced from:
      CefStringTraitsUTF16::to_string(_cef_string_utf16_t const*) in cef_bridge.o
  _cef_string_utf8_to_utf16, referenced from:
      CefStringTraitsUTF16::from_string(char const*, unsigned long, _cef_string_utf16_t*) in cef_bridge.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by SinyimZhi** [comment]
have you unzip the prebuilt package at correct path? Read readme may helps you @luoguilin

**Comment by luoguilin** [comment]
> have you unzip the prebuilt package at correct path? Read readme may helps you @luoguilin

I did put all files into macos/third/cef.
<img width="1512" alt="image" src="https://github.com/hlwhl/webview_cef/assets/16082875/fd86de65-a309-49c5-aa70-539ae7f9c2b4">

**Comment by SinyimZhi** [comment]
@luoguilin oh man, the correct macos folder is same directory with example folder.
![image](https://github.com/hlwhl/webview_cef/assets/49640121/72037f05-f99a-4355-939e-30f4f0fe620d)

**Comment by luoguilin** [comment]
> @luoguilin oh man, the correct macos folder is same directory with example folder. ![image](https://private-user-images.githubusercontent.com/49640121/299526336-72037f05-f99a-4355-939e-30f4f0fe620d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNTM2MjQsIm5iZiI6MTcwNjE1MzMyNCwicGF0aCI6Ii80OTY0MDEyMS8yOTk1MjYzMzYtNzIwMzdmMDUtZjk5YS00MzU1LTkzOWUtMzBmNGYwZmU2MjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAzMjg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYmQ3Y2IwMDYyMTE1N2E2Y2Q1MGQyMDUyNzc3ODdjYzU0NjY3MTYwZDdlMjdhYmVmNmRmNGM2Nzg4YjFjMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h03OwHfSZFmvAYqFx2J38sejeJ-BRQSkQ9vdiLMY92c)

Thank you very much for your help, I successfully solved this problem

**Comment by scalveerne** [comment]
@luoguilin How did you make it work for macOS?
