### ISSUE TITLE
[Help Wanted!][macos]add CEF dependency via podspec

### ISSUE THREAD

**Issue by hlwhl** [hlwhl/webview_cef#11]
I met a problem when integrate cef on macos : add Chromium Embedded Framework.framework dependency via podspec cause link error.
Does anyone have idea about how to solve this issue?
![2341659793888_ pic](https://user-images.githubusercontent.com/7610615/183251777-1fd4bd9b-9027-4257-8c48-1e407c0dc14c.jpg)

**Comment by hlwhl** [comment]
The framework has already imported according to xcode.
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/7610615/183251938-e693749b-3027-422f-8718-c592fe85321f.png">

**Comment by chinabrant** [comment]
可以把代码传上来吗？开个分支，我来看看。

**Comment by hlwhl** [comment]
@chinabrant 感谢关注！podspec配置文件已提交至macos分支，cef framework 需要在这里根据你机器的架构下载 ：https://cef-builds.spotifycdn.com/index.html#macosx64。下载下来的档案解压后复制 Release/Chromium Embedded Framework.framework 到本工程的 macos/third/cef路径下编译即可

**Comment by chinabrant** [comment]
@hlwhl 我这里是一些其它的错误，运行不起来，试了一下，那个路径里面加上斜杠对空格转译后就会出现你那个错误，你可以试试去掉转译的斜杠，空格不用转译试试。还有，你用的哪个flutter版本？我用的stable的 3.0.5 测试的。暂时没有太多时间花在这上面。

**Comment by hlwhl** [comment]
@chinabrant 我这里也是stable 3.0.5. 目前试下来，我这里去掉转译也会报一样的错。直接将framework拖进xcode不会报错，编译也没问题。如果podspec解决不了，只能写一个脚本绕过cocoapod了。

**Comment by chinabrant** [comment]
我在cocoapods提了个issuse， https://github.com/CocoaPods/CocoaPods/issues/11493 感觉还是那个文件名空格的问题。vendored framework这样写是没问题的。

**Comment by chinabrant** [comment]
![1111](https://user-images.githubusercontent.com/3281092/185284189-6d63d379-f650-4e3e-83e0-13d5784264a5.png)
你把Example工程的 other linker flags全部删除试一下。

**Comment by hlwhl** [comment]
> ![1111](https://user-images.githubusercontent.com/3281092/185284189-6d63d379-f650-4e3e-83e0-13d5784264a5.png)
> 你把Example工程的 other linker flags全部删除试一下。

确实是这里的问题👍

**Comment by hlwhl** [comment]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/7610615/185366978-78fcfce7-191f-4ec4-8cd8-8ae3e85ca787.png">
now it's running on mac😁
