### ISSUE TITLE
Check failed: !g_instance error on access again to page

### ISSUE THREAD

**Issue by MobileD3v3l** [hlwhl/webview_cef#117]
Hello,

Following the example proposed in the plugin, if I navigate to that page from a home page it is displayed correctly.

However, when you navigate back to the source page and access in again, the application closes and displays the following message on the terminal:

[0419/092055.443214:FATAL:webview_handler.cc(36)] Verification failed: !g_instance.

What could be the problem?

I have consulted some of the previous issues related to !g_instance, but I have not been able to find the solution.

Greetings

**Comment by SinyimZhi** [comment]
Same question as # 96

**Comment by SinyimZhi** [comment]
Hi, every one. I've merged multi instance and multi window support branch to main. There is a lot of problems might have been resloved. Could you guys help us to verify what we did success and what new problem brought in? @MobileD3v3l

**Comment by MobileD3v3l** [comment]
After some tests it seems working correctly. Only one thing, but I need to investigate it deeper as maybe is something on my implementation, JSchannels seem to be lost the second time the app access the webview.

**Comment by SinyimZhi** [comment]
> After some tests it seems working correctly. Only one thing, but I need to investigate it deeper as maybe is something on my implementation, JSchannels seem to be lost the second time the app access the webview.

Jschannel needs to be injected every time a page is loaded, and it‘s lifecycle is affected by the lifecycle of the page.
