### ISSUE TITLE
macos third/cef/libcef_dll_wrapper.a 这个文件是哪个？

### ISSUE THREAD

**Issue by chinabrant** [hlwhl/webview_cef#12]
那个framework超过100m了，应该要用zip的形式托管到其它的地方。

这个libcef_dll_wrapper.a能发出来一下吗

**Comment by hlwhl** [comment]
[arm64](https://github.com/hlwhl/webview_cef/releases/download/untagged-f95ebb990f106b390e71/CEFbins-mac103.0.12-arm64.zip)
Intel架构稍后会打一个出来。目前打出来的包还需要将多进程的入口手动拷贝到app的framework中，后续我会完善下多进程入口生成流程和打包流程。

**Comment by chinabrant** [comment]
你这个下载不了，找不到。

**Comment by chinabrant** [comment]
发的是.lib的，直接改成.a吗？

**Comment by hlwhl** [comment]
@chinabrant https://github.com/hlwhl/webview_cef/releases/download/untagged-f95ebb990f106b390e71/CEFbins-mac103.0.12-arm64.zip 这个链接哈.lib是windows的

**Comment by chinabrant** [comment]
这个链接下载不了

**Comment by hlwhl** [comment]
@chinabrant https://github.com/hlwhl/webview_cef/releases/download/prebuilt_cef_bin_mac/CEFbins-mac103.0.12-arm64.zip   试试这个呢

**Comment by chinabrant** [comment]
可以了，谢谢。

**Comment by chinabrant** [comment]
我在做我们App的Mac版本，要用到内嵌webview，这个项目后面有什么我能参与的吗？技术栈主要是iOS和Flutter开发。

**Comment by chinabrant** [comment]
code/webview_cef/macos/Classes/CefWrapper.mm:10:9: fatal error: 'include/wrapper/cef_library_loader.h' file not found
#import "include/wrapper/cef_library_loader.h"

**Comment by hlwhl** [comment]
@chinabrant 将windows下的这四个文件拖到xcode中插件的pod里。我之前尝试将这四个文件复制到macos/Classes里，编译会报错，还没来得及看原因。
![image](https://user-images.githubusercontent.com/7610615/185550702-5e96953e-627c-41a6-9232-9315a6b41229.png)

**Comment by chinabrant** [comment]
include文件夹也要拖过去吧？

**Comment by hlwhl** [comment]
@chinabrant include我刚提交了，你可以拉一下代码

**Comment by chinabrant** [comment]
> 

这个有x86的吗？这个是arm64的。

**Comment by hlwhl** [comment]
@chinabrant https://github.com/hlwhl/webview_cef/releases/download/prebuilt_cef_bin_mac_intel/mac103.0.12-Intel.zip intel架构。现在问题还比较多resize Mac会花屏
