### ISSUE TITLE
Some sites in Chinese language (x.com, facebook.com, tiktok.com)

### ISSUE THREAD

**Issue by dzen1984** [hlwhl/webview_cef#125]
Some sites in Chinese language (x.com, facebook.com, tiktok.com).
I launched it on macOS. The macOS is in English, I'm not in China.
I tried to change a user agent. Nothing help.

Does anyone know why so?

**Comment by AndriiReverchuk** [comment]
Hello @SinyimZhi,

First and foremost, I want to commend you for your outstanding work on this package. Your efforts are truly appreciated, and the functionality provided is excellent.

Regarding the current issue, I would like to ask if you could add language as an option within the package settings. Alternatively, could the default language be set to English? This adjustment would greatly help users who are experiencing language-related issues.

Thank you for your consideration and for your continued dedication to improving this package.

Best regards, 
@AndriiReverchuk

**Comment by SinyimZhi** [comment]
> Hello @SinyimZhi,
> 
> First and foremost, I want to commend you for your outstanding work on this package. Your efforts are truly appreciated, and the functionality provided is excellent.
> 
> Regarding the current issue, I would like to ask if you could add language as an option within the package settings. Alternatively, could the default language be set to English? This adjustment would greatly help users who are experiencing language-related issues.
> 
> Thank you for your consideration and for your continued dedication to improving this package.
> 
> Best regards, @AndriiReverchuk

Thank you for your suggestion. Cause the default locale language for CEF is English, just remove the locale setting code I mentioned earlier. We will try to provide a DART level configuration item interface in the future to allow developers to set some CEF initialization settings
