### ISSUE TITLE
Play MP4 video

### ISSUE THREAD

**Issue by MobileD3v3l** [hlwhl/webview_cef#126]
Hi,

When I'm trying to reproduce .mp4 videos, I get this error:

Uncaught (in promise) NotSupportedError: The element has no supported sources.", source: about:srcdoc

There are som codecs I must added?

Thanks

**Comment by SinyimZhi** [comment]
The cef prebuilt package didn't support h264(offically, cef not support by default).  You can google how to add h264 support for cef, then build your own cef prebuilt package to replace the one we afford.

**Comment by MobileD3v3l** [comment]
Well, thanks, I'll check it out. But any advice on how to achieve this will be welcome.

**Comment by hlwhl** [comment]
> Well, thanks, I'll check it out. But any advice on how to achieve this will be welcome.

You need to build cef framework by yourself with releated switches on. Reference: https://magpcss.org/ceforum/viewtopic.php?f=6&t=13515.
