### ISSUE TITLE
linux 支持

### ISSUE THREAD

**Issue by 1056824847** [hlwhl/webview_cef#13]
这个插件很不错，请问这个插件到时会支持linux吗

**Comment by hlwhl** [comment]
目前会先完善macos的支持

**Comment by DaBinGe** [comment]
请尽快支持Linux可以吗？我们已用在Windows版，适配Linux版也急需此插件。感谢，Best wishes！

**Comment by hlwhl** [comment]
> 请尽快支持Linux可以吗？我们已用在Windows版，适配Linux版也急需此插件。感谢，Best wishes！

最近工作较忙，会尽量在q2提供linux支持

**Comment by DaBinGe** [comment]
> 

好的，期待Linux版上线

**Comment by SinyimZhi** [comment]
> > 请尽快支持Linux可以吗？我们已用在Windows版，适配Linux版也急需此插件。感谢，Best wishes！
> 
> 最近工作较忙，会尽量在q2提供linux支持

这个插件很不错，有些相关问题想和您交流，我已经向您的邮箱发了邮件，希望能得到您的回复。

**Comment by leisu1** [comment]
> > 请尽快支持Linux可以吗？我们已用在Windows版，适配Linux版也急需此插件。感谢，Best wishes！
> 
> 最近工作较忙，会尽量在q2提供linux支持

大佬  请问一下linux的有进展吗  预计什么时候能发布啊

**Comment by SinyimZhi** [comment]
@DaBinGe @leisu1 @1056824847 linux版目前已经合入main。
