### ISSUE TITLE
Can't pass Apple review with the webview_cef

### ISSUE THREAD

**Issue by antonsivov-konomic** [hlwhl/webview_cef#147]
Hello,
Version is 0.2
I got the following answer from Apple Review Team:

**Describe the bug**
Since a cap of weeks ago I can't publish the new version of mine application to App Store. The Apple Review Team sent the following message.

    Review date: August 16, 2024

    Build version reviewed: 1.0.0 (24)

    Guideline 2.5.1 - Performance - Software Requirements

    Your app uses or references the following non-public or deprecated APIs:

    Contents/Frameworks/Chromium Embedded Framework.framework/Versions/A/Chromium Embedded Framework

    Classes:

    • CAContext

    • NSAccessibilityRemoteUIElement

    • NSNextStepFrame

    • NSThemeFrame

    • CALayerHost

    Symbols:

    • _sandbox_compile_string

    • _dyld_dynamic_interpose

    • __NSAppendToKillRing

    • _AudioDeviceDuck

    • __kLSOpenOptionAddToRecentsKey

    • __kCFSystemVersionProductVersionExtraKey

    • _CTFontDescriptorIsSystemUIFont

    • __NSYankFromKillRing

    • __NSInitializeKillRing

    • __CFCopySystemVersionDictionary

    • __CFURLCopyPropertyListRepresentation

    • __kLSOpenOptionActivateKey

    • _CGFontRenderingGetFontSmoothingDisabled

    • __kCFSystemVersionProductNameKey

    • __NSNewKillRingSequence

    • _IOBluetoothPreferenceSetControllerPowerState

    • _sandbox_set_param

    • _CGSSetDenyWindowServerConnections

    • __kLSOpenOptionHideKey

    • _CGDisplayUsesForceToGray

    • __LSSetApplicationLaunchServicesServerConnectionStatus

    • _responsibility_get_pid_responsible_for_pid

    • __kCFSystemVersionProductVersionKey

    • _sandbox_free_params

    • __kCFSystemVersionBuildVersionKey

    • _sandbox_create_params

    • __kLSOpenOptionBackgroundLaunchKey

    • _NSTextInputReplacementRangeAttributeName

    • _CFStringGetRangeOfCharacterClusterAtIndex

    • _SetApplicationIsDaemon

    • __LSOpenURLsWithCompletionHandler

    • __NSSetKillRingToYankedState

    • __kLSOpenOptionArgumentsKey

    • _responsibility_spawnattrs_setdisclaim

    • __CFURLCreateFromPropertyListRepresentation

    • _sandbox_free_profile

    • __kLSOpenOptionPreferRunningInstanceKey

    The use of non-public or deprecated APIs is not permitted on the App Store, as they can lead to a poor user experience should these APIs change and are otherwise not supported on Apple platforms.

    Next Steps

    It would be appropriate to revise your binary and remove any references to the non-public or deprecated APIs identified above.

    If you are using third-party libraries, update to the most recent version of those libraries. If you do not have access to the libraries' source, the following command line tools can help you identify the location of problematic code:

        The "strings" tool can output a list of the methods the library calls.

        The "otool -ov" tool will output the Objective-C class structures and their defined methods.

    Resources

        We are constantly reevaluating and identifying non-public APIs that you may have been using for an extended period of time. Always use public APIs and frameworks and ensure they are up to date.

        If there are no alternatives for providing the functionality your app requires, you can use Feedback Assistant to submit an enhancement request.

    Support

        Reply to this message in your preferred language if you need assistance. If you need additional support, use the Contact Us module.

        Consult with fellow developers and Apple engineers on the Apple Developer Forums.

        Help improve the review process or identify a need for clarity in our policies by suggesting guideline changes.

        Request a 30-minute online meeting with an App Review expert to discuss the guidelines and best practices for a smooth review process.

Can you please remove the deprecated calls and symbols?

**To Reproduce**

    Make build/download existing of CEF universal build
    Include the CEF to a project (we use [webview_cef](https://pub.dev/packages/webview_cef) component in our case.
    Publish the assembly to App Store
    See error

**Expected behavior**
App review should not have any errors in CEF library

**Screenshots**
N/A

**Versions (please complete the following information):**

    OS: [MacOS 14.0]
    CEF Version: [128.4.5+gc1d356f+chromium-128.0.6613.18]    
    webview_ce - 0.2.0

Additional context
N/A

Need your assistance with the issue. No I can't user the view in mine MacOS application

**Comment by hlwhl** [comment]
You can't pass apple's review when using CEF. There's no chromium based application/browser in  mac appstore. If you really want your app  live on appstore, use webkit webview instead.
