### ISSUE TITLE
mac平台跑不通求大佬指点

### ISSUE THREAD

**Issue by Mr-Hsiao** [hlwhl/webview_cef#16]
mac平台跑不通求大佬指点，inter架构cpu,下载目录是否放入macos平台下？配置：macos/third/cef/下载目录
![{874B67DD-35E3-9875-3503-152D7301CD20}](https://user-images.githubusercontent.com/90084202/191965832-e517bdbd-1edd-4b06-b908-6e345b3e39fb.jpg)

**Comment by hlwhl** [comment]
目录结构如下：
<img width="386" alt="image" src="https://user-images.githubusercontent.com/7610615/191980690-4069547a-7ced-41ec-a733-6be3c6dac9b8.png">

目录结构没问题就确认下载的包是否为x86架构

**Comment by Mr-Hsiao** [comment]
例子已跑通，感谢大佬支持
