### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by tuhao-world** [hlwhl/webview_cef#20]
该插件无法通过编译，所有日志如下：
Launching lib/main.dart on macOS in debug mode...
Building macOS application...
Undefined symbols for architecture x86_64:
  "CefURIEncode(CefStringBase<CefStringTraitsUTF16> const&, bool)", referenced from:
      (anonymous namespace)::GetDataURI(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in cef_bridge.o
  "CefInitialize(CefMainArgs const&, CefStructBase<CefSettingsTraits> const&, scoped_refptr<CefApp>, void*)", referenced from:
      +[CefWrapper startCef] in CefWrapper.o
  "CefCurrentlyOn(cef_thread_id_t)", referenced from:
      SimpleApp::OnContextInitialized() in cef_bridge.o
      SimpleHandler::OnTitleChange(scoped_refptr<CefBrowser>, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
      SimpleHandler::OnAfterCreated(scoped_refptr<CefBrowser>) in cef_bridge.o
      SimpleHandler::DoClose(scoped_refptr<CefBrowser>) in cef_bridge.o
      SimpleHandler::OnBeforeClose(scoped_refptr<CefBrowser>) in cef_bridge.o
      SimpleHandler::OnLoadError(scoped_refptr<CefBrowser>, scoped_refptr<CefFrame>, cef_errorcode_t, CefStringBase<CefStringTraitsUTF16> const&, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
      SimpleHandler::CloseAllBrowsers(bool) in cef_bridge.o
      ...
  "CefBase64Encode(void const*, unsigned long)", referenced from:
      (anonymous namespace)::GetDataURI(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in cef_bridge.o
  "CefExecuteProcess(CefMainArgs const&, scoped_refptr<CefApp>, void*)", referenced from:
      +[CefWrapper init] in CefWrapper.o
  "CefQuitMessageLoop()", referenced from:
      SimpleHandler::OnBeforeClose(scoped_refptr<CefBrowser>) in cef_bridge.o
  "CefDoMessageLoopWork()", referenced from:
      +[CefWrapper doMessageLoopWork] in CefWrapper.o
  "CefBrowserHost::CreateBrowser(CefWindowInfo const&, scoped_refptr<CefClient>, CefStringBase<CefStringTraitsUTF16> const&, CefStructBase<CefBrowserSettingsTraits> const&, scoped_refptr<CefDictionaryValue>, scoped_refptr<CefRequestContext>)", referenced from:
      SimpleApp::OnContextInitialized() in cef_bridge.o
  "CefBrowserView::GetForBrowser(scoped_refptr<CefBrowser>)", referenced from:
      SimpleHandler::OnTitleChange(scoped_refptr<CefBrowser>, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
  "CefCommandLine::GetGlobalCommandLine()", referenced from:
      SimpleHandler::IsChromeRuntimeEnabled() in cef_bridge.o
  "CefScopedLibraryLoader::Load(bool)", referenced from:
      CefScopedLibraryLoader::LoadInMain() in CefWrapper.o
  "CefScopedLibraryLoader::CefScopedLibraryLoader()", referenced from:
      +[CefWrapper init] in CefWrapper.o
  "CefScopedLibraryLoader::~CefScopedLibraryLoader()", referenced from:
      +[CefWrapper init] in CefWrapper.o
  "cef::logging::LogMessage::LogMessage(char const*, int, int)", referenced from:
      SimpleApp::OnContextInitialized() in cef_bridge.o
      SimpleHandler::SimpleHandler(bool) in cef_bridge.o
      SimpleHandler::SimpleHandler(bool) in cef_bridge.o
      SimpleHandler::OnTitleChange(scoped_refptr<CefBrowser>, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
      scoped_refptr<CefBrowserView>::operator->() const in cef_bridge.o
      scoped_refptr<CefWindow>::operator->() const in cef_bridge.o
      SimpleHandler::OnAfterCreated(scoped_refptr<CefBrowser>) in cef_bridge.o
      ...
  "cef::logging::LogMessage::~LogMessage()", referenced from:
      SimpleApp::OnContextInitialized() in cef_bridge.o
      SimpleHandler::SimpleHandler(bool) in cef_bridge.o
      SimpleHandler::SimpleHandler(bool) in cef_bridge.o
      SimpleHandler::OnTitleChange(scoped_refptr<CefBrowser>, CefStringBase<CefStringTraitsUTF16> const&) in cef_bridge.o
      scoped_refptr<CefBrowserView>::operator->() const in cef_bridge.o
      scoped_refptr<CefWindow>::operator->() const in cef_bridge.o
      SimpleHandler::OnAfterCreated(scoped_refptr<CefBrowser>) in cef_bridge.o
      ...
  "_cef_string_utf16_clear", referenced from:
      CefWindowInfoTraits::clear(_cef_window_info_t*) in cef_bridge.o
      CefStringTraitsUTF16::clear(_cef_string_utf16_t*) in cef_bridge.o
      CefBrowserSettingsTraits::clear(_cef_browser_settings_t*) in cef_bridge.o
      CefStringTraitsUTF16::clear(_cef_string_utf16_t*) in CefWrapper.o
      CefSettingsTraits::clear(_cef_settings_t*) in CefWrapper.o
  "_cef_string_utf16_to_utf8", referenced from:
      CefStringTraitsUTF16::to_string(_cef_string_utf16_t const*) in cef_bridge.o
  "_cef_string_utf8_clear", referenced from:
      CefStringTraitsUTF16::to_string(_cef_string_utf16_t const*) in cef_bridge.o
  "_cef_string_utf8_to_utf16", referenced from:
      CefStringTraitsUTF16::from_string(char const*, unsigned long, _cef_string_utf16_t*) in cef_bridge.o
      CefStringTraitsUTF16::from_string(char const*, unsigned long, _cef_string_utf16_t*) in CefWrapper.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at /System/Volumes/Data/SWE/macOS/BuildRoots/b8ff8433dc/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/rsync.c(244) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Exception: Build process failed

**Comment by tuhao-world** [comment]
这应该是部分日志

**Comment by hlwhl** [comment]
检查一下是否下载并解压放置了readme中提到的对应架构的库压缩包？

**Comment by iOSluozhiping** [comment]
我也遇到这个问题 请问放置到哪个目录下

**Comment by iOSluozhiping** [comment]
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/28723827/195537624-9cf49c62-fa78-4b40-b6dd-319cbe3bbc4e.png">
您好 是这样吧 但还是报错

**Comment by iOSluozhiping** [comment]
我是intel的 下载了intel的包

**Comment by hlwhl** [comment]
@iOSluozhiping 删除example/macos/Profile.lock后，在example中执行下flutter clean后再次尝试运行

**Comment by iOSluozhiping** [comment]
可以了 谢谢 如果我想在自己项目里用 该放到哪里

**Comment by hlwhl** [comment]
@iOSluozhiping 目前可以放在pub自动下载的缓存文件里，后续会想办法优化依赖的下载

**Comment by iOSluozhiping** [comment]
在我的项目里运行时候报错
<img width="555" alt="image" src="https://user-images.githubusercontent.com/28723827/195555913-b6621d5a-e3b3-47b1-899c-50fb56af3878.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/28723827/195558262-334fd883-8777-481e-ab0f-e7e36c3855d7.png">

**Comment by iOSluozhiping** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/28723827/195575271-8058a508-06ea-4605-bf2a-6d1e459562b0.png">
您好 用你的demo在mac上打开pdf 闪退了

**Comment by hlwhl** [comment]
> <img alt="image" width="860" src="https://user-images.githubusercontent.com/28723827/195575271-8058a508-06ea-4605-bf2a-6d1e459562b0.png">
> 
> 您好 用你的demo在mac上打开pdf 闪退了

#22
