### ISSUE TITLE
autoplay video not working

### ISSUE THREAD

**Issue by okiabrian123** [hlwhl/webview_cef#28]
in chrome the video autoplay is disabled unless it is whitelisted, can we add an argument so that the video autoplay can run?`--autoplay-policy=no-user-gesture-required`

**Comment by hlwhl** [comment]
https://github.com/hlwhl/webview_cef/blob/3aece36f32e3a575879473c6f4c1f38f681e9682/common/webview_app.h#L21-L30

Yes, you can add any options in the code above to make it working.

**Comment by okiabrian123** [comment]
thank you

**Comment by okiabrian123** [comment]
>     void OnBeforeCommandLineProcessing(
>                                        const CefString& process_type,
>                                        CefRefPtr<CefCommandLine> command_line) override {
>                                            command_line->AppendSwitch("disable-gpu");
>                                            command_line->AppendSwitch("disable-gpu-compositing");
>                                            command_line->AppendSwitchWithValue("autoplay-policy", "no-user-gesture-required"); //auto play video
>                                            #ifdef __APPLE__
>                                                 command_line->AppendSwitch("use-mock-keychain");
>                                                 command_line->AppendSwitch("single-process");
>                                            #endif
>                                        }
