### ISSUE TITLE
Build error on windows 10

### ISSUE THREAD

**Issue by stevenBang** [hlwhl/webview_cef#3]
I opened an empty project
And introduce webview_cef
The following error is reported when it starts up
Can any expert help?

`C:\Users\StevenXiao\StudioProjects\windows_cmf\windows\flutter\ephemeral\.plugin_symlinks\webview_cef\windows\simple_handler.h(1,1): error C2220: �H�Uĵ�i�������~�B�z [C:\Users\StevenXiao\StudioProjects\windows_cmf\build\windows\plugins\webview_cef\webview_cef_plugin.vcxproj]
C:\Users\StevenXiao\StudioProjects\windows_cmf\windows\flutter\ephemeral\.plugin_symlinks\webview_cef\windows\simple_handler.h(1,1): warning C4819: �ɮקt���L�k�b�ثe�r�X�� (950) �����ܪ��r���C�ХH Unicode �榡�x�s�ɮץH�����ƿ� [C:\Users\StevenXiao\StudioProjects\windows_cmf\build\windows\plugins\webview_cef\webview_cef_plugin.vcxproj]
C:\Users\StevenXiao\StudioProjects\windows_cmf\windows\flutter\ephemeral\.plugin_symlinks\webview_cef\windows\simple_handler.h(1,1): error C2220: �H�Uĵ�i�������~�B�z [C:\Users\StevenXiao\StudioProjects\windows_cmf\build\windows\plugins\webview_cef\webview_cef_plugin.vcxproj]
C:\Users\StevenXiao\StudioProjects\windows_cmf\windows\flutter\ephemeral\.plugin_symlinks\webview_cef\windows\simple_handler.h(1,1): warning C4819: �ɮקt���L�k�b�ثe�r�X�� (950) �����ܪ��r���C�ХH Unicode �榡�x�s�ɮץH�����ƿ� [C:\Users\StevenXiao\StudioProjects\windows_cmf\build\windows\plugins\webview_cef\webview_cef_plugin.vcxproj]
C:\Users\StevenXiao\StudioProjects\windows_cmf\windows\flutter\ephemeral\.plugin_symlinks\webview_cef\windows\simple_handler.h(1,1): error C2220: �H�Uĵ�i�������~�B�z [C:\Users\StevenXiao\StudioProjects\windows_cmf\build\windows\plugins\webview_cef\webview_cef_plugin.vcxproj]
C:\Users\StevenXiao\StudioProjects\windows_cmf\windows\flutter\ephemeral\.plugin_symlinks\webview_cef\windows\simple_handler.h(1,1): warning C4819: �ɮקt���L�k�b�ثe�r�X�� (950) �����ܪ��r���C�ХH Unicode �榡�x�s�ɮץH�����ƿ� [C:\Users\StevenXiao\StudioProjects\windows_cmf\build\windows\plugins\webview_cef\webview_cef_plugin.vcxproj]
C:\Users\StevenXiao\StudioProjects\windows_cmf\windows\flutter\ephemeral\.plugin_symlinks\webview_cef\windows\simple_handler.h(1,1): error C2220: �H�Uĵ�i�������~�B�z [C:\Users\StevenXiao\StudioProjects\windows_cmf\build\windows\plugins\webview_cef\webview_cef_plugin.vcxproj]
C:\Users\StevenXiao\StudioProjects\windows_cmf\windows\flutter\ephemeral\.plugin_symlinks\webview_cef\windows\simple_handler.h(1,1): warning C4819: �ɮקt���L�k�b�ثe�r�X�� (950) �����ܪ��r���C�ХH Unicode �榡�x�s�ɮץH�����ƿ� [C:\Users\StevenXiao\StudioProjects\windows_cmf\build\windows\plugins\webview_cef\webview_cef_plugin.vcxproj]
Exception: Build process failed.
`

**Comment by hlwhl** [comment]
check your flutter version. upgrade flutter to 3.0.3.
there is a bug in flutter 3.0 that none utf8 system env cause build failure

**Comment by stevenBang** [comment]
OK, thanks~
Switching to flutter channel 'master'

**Comment by stevenBang** [comment]
@hlwhl hlwhl sorry for the same error
Have you encountered the same problem?

Flutter 3.1.0-0.0.pre.1468 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1add0d790d (3 hours ago) • 2022-07-01 00:39:07 -0400
Engine • revision caec3e305a
Tools • Dart 2.18.0 (build 2.18.0-242.0.dev) • DevTools 2.14.1

**Comment by hlwhl** [comment]
![image](https://user-images.githubusercontent.com/7610615/176856895-361518e2-bed0-43be-893a-e64942b2bc5c.png)
i suspect it's a file encoding issue. would you please go to control panel -> Region, check the utf-8 option, restart computer and try again?

**Comment by hlwhl** [comment]
@stevenBang i can reproduce this issue, i'll fix it later

**Comment by hlwhl** [comment]
#4 fixed @stevenBang

**Comment by stevenBang** [comment]
@hlwhl ok thank you very much for your help!
