### ISSUE TITLE
构建失败 windows

### ISSUE THREAD

**Issue by newer-android** [hlwhl/webview_cef#35]
加入组件构建时提示 LINK : fatal error LNK1104: �޷����ļ���E:\Flutter2020\hd_smart_dsp_tf\windows\flutter\ephemeral\.plugin_symlinks\webview_cef\windows\cefbins\debug\libcef.lib�� [E:\Flutter2020\hd_smart_dsp_tf\build\windows\plugins\webview_cef\webview_cef_plugin.vcxproj]
Exception: Build process failed.，下载Demo和引入都是这哥错误

**Comment by hlwhl** [comment]
看下 \webview_cef\windows\cefbins\ 是否存在，在编译时cmake脚本会自动下载cef的二进制包。可以看下是否下载失败。

**Comment by newer-android** [comment]
E:\Flutter2020\webview_cef-main\windows\cefbins  这个文件夹是空的

**Comment by newer-android** [comment]
这是下载失败了吗？

**Comment by newer-android** [comment]
Flutter2020\webview_cef-main\example\windows\flutter\ephemeral\.plugin_symlinks\webview_cef\windows\cefbins\这个没有这个文件夹  example底下的windows

**Comment by hlwhl** [comment]
> 这是下载失败了吗？

是的，下载失败了

**Comment by hlwhl** [comment]
> 这是下载失败了吗？

https://github.com/hlwhl/webview_cef/releases/download/prebuilt_cef_bin/webview_cef_bin_0.0.1_101.0.18+chromium-101.0.4951.67_windows64.zip  可以手动下载下，在release里

**Comment by newer-android** [comment]
好的 谢谢 我试试

**Comment by newer-android** [comment]
使用下载的Demo运行无问题，集成到项目里提示错误Could not load chrome_100_percent.pak、 Could not load chrome_200_percent.pak、Network service crashed, restarting service  会打开多个桌面

**Comment by newer-android** [comment]
alloy_main_delegate.cc(563)] Could not load chrome_200_percent.pak

**Comment by newer-android** [comment]
是需要配置什么信息吗

**Comment by newer-android** [comment]
一直弹空白的窗口，关闭就打开

**Comment by hlwhl** [comment]
chrome_200_percent.pak， 看错误是因为有一些resources文件没有复制到你打出来的exe旁边，能否对比下demo和你的app打包后产物文件的差异？

**Comment by newer-android** [comment]
加载全景文件，提示 ERROR:  Adobe Flashplayer ir HTML5 Browser with WebGL or CSS3D support required!,我该如何设置以支持这些属性

**Comment by Doflatango** [comment]
> chrome_200_percent.pak， 看错误是因为有一些resources文件没有复制到你打出来的exe旁边，能否对比下demo和你的app打包后产物文件的差异？

@hlwhl  请问 `chrome_100_percent.pak`、`chrome_200_percent.pak` 这两个文件是从哪里来的？https://github.com/hlwhl/webview_cef/releases/download/prebuilt_cef_bin/webview_cef_bin_0.0.1_101.0.18+chromium-101.0.4951.67_windows64.zip 不包含这两个文件。

实际运行虽然会打印下面的警告信息，但是并不影响运行：
> [1228/132236.172:ERROR:alloy_main_delegate.cc(554)] Could not load chrome_100_percent.pak
[1228/132236.172:ERROR:alloy_main_delegate.cc(563)] Could not load chrome_200_percent.pak

**Comment by hlwhl** [comment]
> > chrome_200_percent.pak， 看错误是因为有一些resources文件没有复制到你打出来的exe旁边，能否对比下demo和你的app打包后产物文件的差异？
> 
> @hlwhl 请问 `chrome_100_percent.pak`、`chrome_200_percent.pak` 这两个文件是从哪里来的？https://github.com/hlwhl/webview_cef/releases/download/prebuilt_cef_bin/webview_cef_bin_0.0.1_101.0.18+chromium-101.0.4951.67_windows64.zip 不包含这两个文件。
> 
> 实际运行虽然会打印下面的警告信息，但是并不影响运行：
> 
> > [1228/132236.172:ERROR:alloy_main_delegate.cc(554)] Could not load chrome_100_percent.pak
> > [1228/132236.172:ERROR:alloy_main_delegate.cc(563)] Could not load chrome_200_percent.pak

@Doflatango 是cef附带的资源文件，应该与高DPI有关，测试时确实不是必要文件，因此没有放入预编译包中。

**Comment by Doflatango** [comment]
> @Doflatango 是cef附带的资源文件，应该与高DPI有关，测试时确实不是必要文件，因此没有放入预编译包中。

@hlwhl 谢谢回答，这两个文件与其它资源文件比起来算是比较小，我认为还是可以放进去插件里面，以避免一些可能存在的不必要的问题。

**Comment by hlwhl** [comment]
> > @Doflatango 是cef附带的资源文件，应该与高DPI有关，测试时确实不是必要文件，因此没有放入预编译包中。
> 
> @hlwhl 谢谢回答，这两个文件与其它资源文件比起来算是比较小，我认为还是可以放进去插件里面，以避免一些可能存在的不必要的问题。

@Doflatango 嗯，下个版本升级cef时会带上这些文件

**Comment by newer-android** [comment]
加载3D全景提示
![错误](https://user-images.githubusercontent.com/7529735/213097163-30ad797d-4f89-465e-930f-27dcd9157815.png)
，这个如何设置可以做到支持

**Comment by hlwhl** [comment]
> 加载3D全景提示
> ![错误](https://user-images.githubusercontent.com/7529735/213097163-30ad797d-4f89-465e-930f-27dcd9157815.png)
> ，这个如何设置可以做到支持

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/7610615/215249862-69f935a6-bb1c-43a1-882f-83b914a037ef.png">
@newer-android 你使用的哪个平台？我这里试打开你那个链接是没问题的

**Comment by hlwhl** [comment]
@newer-android [CEF开启WEBGL支持](https://blog.51cto.com/u_15067227/4001926?u_atoken=a1fec2dd-310d-4d52-b582-dbbd8cfad492&u_asession=0132p1Z2ahI8J8mlLBZSLYxkfFCGHObHAhTLVuX6fQIOdE4RUMq-lXx97s1FPeGQe_X0KNBwm7Lovlpxjd_P_q4JsKWYrT3W_NKPr8w6oU7K-MHUUWSt2fmy272SO3izCTiavZuquXuuDfBlaKI5LOmmBkFo3NEHBv0PZUm6pbxQU&u_asig=05_gA_ZE-974KaLp64DiQFLCj24fFI6iMSG6VdMB6HsRM0Z5LX_XuoE5hC8FxQOfpXKm0z-NLCiekFOXh9V_4XwHCh6uCGfwTN2hKWL3sPYRFsVi95rqTu5OKWDForX5zcs-xrCY7kWpE_oy2SJwu--6FUhlZmKivk-bjYS5wFUA39JS7q8ZD7Xtz2Ly-b0kmuyAKRFSVJkkdwVUnyHAIJzSbNOMQInebuAXHL5bkSU3cc0gdBPsSpPes3JOXsziFWntwrbb2HXtH8Nt-UUfBaCe3h9VXwMyh6PgyDIVSG1W-JKdezUdqUL5juuHusicp7Xsc5ggf623lX74vpg8_18XQT-QEli0GyRXCq7Sxaa__RJtoPC3kQv9HHhh5tmRJUmWspDxyAEEo4kbsryBKb9Q&u_aref=G%2BCcqGdOKNtYHAqrZ7yOyFb8wL0%3D) 可以尝试下这个链接呢。在webview_app.h这个文件中设置。

**Comment by newer-android** [comment]
@ hlwhl   windows11,修改了还不行
![企业微信截图_16749751591916](https://user-images.githubusercontent.com/7529735/215310268-5742a306-bc7c-4ba7-add4-b7dbec5c3bd2.png)
```

 void OnBeforeCommandLineProcessing(
                                       const CefString& process_type,
                                       CefRefPtr<CefCommandLine> command_line) override {
                                           command_line->AppendSwitch("disable-gpu");
                                           command_line->AppendSwitch("disable-gpu-compositing");
                                           command_line->AppendSwitchWithValue("enable-webgl", "1");
                                           command_line->AppendSwitchWithValue("ignore-gpu-blacklist", "1");
                                           command_line->AppendSwitchWithValue("allow-file-access-from-files", "1");
                                           #ifdef __APPLE__
                                                command_line->AppendSwitch("use-mock-keychain");
                                                command_line->AppendSwitch("single-process");
                                           #endif
                                       }
```
```

// command_line->AppendSwitch("disable-gpu");
                                           //command_line->AppendSwitch("disable-gpu-compositing");
                                           command_line->AppendSwitchWithValue("enable-webgl", "1");
                                           command_line->AppendSwitchWithValue("ignore-gpu-blacklist", "1");
                                           command_line->AppendSwitchWithValue("allow-file-access-from-files", "1");
                                           #ifdef __APPLE__
                                                command_line->AppendSwitch("use-mock-keychain");
                                                command_line->AppendSwitch("single-process");
                                           #endif
```
