### ISSUE TITLE
There is no prebuilt cef bundles from arm64

### ISSUE THREAD

**Issue by millie-molly** [hlwhl/webview_cef#37]

**Comment by hlwhl** [comment]
Could you specify which platform you are building?

**Comment by millie-molly** [comment]
I am trying to build macOS.
clicked arm64 download link and I got Not Found

**Comment by hlwhl** [comment]
Fixed, please try again. I didn't notice the link is outdated.

**Comment by millie-molly** [comment]
it works!! thanks a lot . 
do you have any plan to make javascript handler?

**Comment by hlwhl** [comment]
> it works!! thanks a lot .
> do you have any plan to make javascript handler?

Already in the todo list : )
