### ISSUE TITLE
[Feature] iOS and android support

### ISSUE THREAD

**Issue by CaptainDario** [hlwhl/webview_cef#44]
I am curious if there are plans to support android and iOS.
This would be nice because then all platforms would use the same webview and support the same features.

**Comment by hlwhl** [comment]
Since CEF does not support mobile devices, this package will not support use on mobile devices. It is recommended to pay attention to the official webview package: webview_flutter.

**Comment by CaptainDario** [comment]
Thank you for this info, I didn't know that CEF does not support them. Would have been nice to have a chromium based web view on all platforms.

**Comment by wanjm** [comment]
what is the difference between this one to webview_flutter; why doen it not support mobile?

**Comment by hlwhl** [comment]
> what is the difference between this one to webview_flutter; why doen it not support mobile?

The plugin is powered by CEF which is a desktop chromium embedding SDK.
