### ISSUE TITLE
Not support high dpi

### ISSUE THREAD

**Issue by stevenBang** [hlwhl/webview_cef#5]
@hlwhl Thank you for your support on the previous issue!

Does it not support high dpi?
and running into some performance issues
Is it because I am using debug mode?
If it's just a simple display of youtube, it will also lag
<img width="466" alt="截圖 2022-07-04 上午11 44 54" src="https://user-images.githubusercontent.com/68453012/177077947-0f31fb10-febf-4bcd-9069-6827e2694d67.png">

**Comment by hlwhl** [comment]
#9 fixed
