### ISSUE TITLE
Can I load local html resources and if so what should I do

### ISSUE THREAD

**Issue by jhaikun** [hlwhl/webview_cef#53]

**Comment by hlwhl** [comment]
Could you provide more information about the issue? Tested on my machine, load local file is avaliable.
![image](https://github.com/hlwhl/webview_cef/assets/7610615/2e89c2af-8341-4c19-a023-365b411e3dd4)

**Comment by jhaikun** [comment]
![image](https://github.com/hlwhl/webview_cef/assets/79888807/9376c51b-9063-4679-b5a7-2b0b5b8874da)
![image](https://github.com/hlwhl/webview_cef/assets/79888807/f4f0545c-622d-456f-b268-cd24c97eed50)
![image](https://github.com/hlwhl/webview_cef/assets/79888807/359f1a1c-1b02-43cc-961e-73b72a9505a7)

Glad to receive your reply
I think I made a mistake now I'm using it like this can you tell me the correct usage
Can I manipulate the cache
thank you

**Comment by hlwhl** [comment]
@jhaikun Have a try on using absolute path?

**Comment by jhaikun** [comment]
I successfully solved this problem using the absolute path
Can I manipulate the cache

**Comment by hlwhl** [comment]
> 

@jhaikun What do you want to do with cache? You can disable cache by set options to cef.
