### ISSUE TITLE
[request] Any plan on making it support Linux？

### ISSUE THREAD

**Issue by homels** [hlwhl/webview_cef#58]

**Comment by hlwhl** [comment]
Working on linux support right now

**Comment by homels** [comment]
> Working on linux support right now.

cooooool!

**Comment by Kofhein** [comment]
Hi, if you need help with Linux - I can help , already got it working for about half a year

**Comment by hlwhl** [comment]
> 

@SinyimZhi is working on linux support.

**Comment by homels** [comment]
> Hi, if you need help with Linux - I can help , already got it working for about half a year

Okay, I think I need some help. Where should I get support

**Comment by SinyimZhi** [comment]
Everyone can try webview_cef plugin support Linux on the branch "linux". we have already support linux but we decide to build a unified interface layer for all three platforms, and provide unified CEF version prebuilt packages. It's the last work before we merge branch linux to main, and  it will be completed soon. @hlwhl @homels @Kofhein

**Comment by homels** [comment]
> Everyone can try webview_cef plugin support Linux on the branch "linux". we have already support linux but we decide to build a unified interface layer for all three platforms, and provide unified CEF version prebuilt packages. It's the last work before we merge branch linux to main, and it will be completed soon. @hlwhl @homels @Kofhein

Okay, I'm paying attention to the Linux branch. In fact, every time your team has a commit on the Linux branch, I will pull it down and try it out. 

Actually, I am learning and comparing various ways to achieve it.  ：）

**Comment by SinyimZhi** [comment]
@homels linux branch has been merged to main, we rebuild middle interface with almost C code. And we will solve the IME problem for third-party inputting method recently.
