### ISSUE TITLE
Keyboard does not work on open sites

### ISSUE THREAD

**Issue by reisclaudio** [hlwhl/webview_cef#70]
I can't use the keyboard to type into fields within loaded sites. Is this normal for the library or some bug?

**Comment by hotdang-ca** [comment]
This actually still seems to be an issue. Why was it closed?

**Comment by RubinTry** [comment]
这个问题依然存在，windows11系统上，用了这个webview后，webview内无法使用键盘，插件版本0.1.0

**Comment by xianxuzhen** [comment]
windows11系统上，用了这个webview后，webview内无法使用键盘，插件版本0.1.0

**Comment by jlcool** [comment]
@SinyimZhi @hlwhl Can you help me take a look at this problem

**Comment by hlwhl** [comment]
> @SinyimZhi @hlwhl Can you help me take a look at this problem

Which platform you encountered this issue? Please provide more details.

**Comment by jlcool** [comment]
> > @SinyimZhi @hlwhl Can you help me take a look at this problem
> 
> Which platform you encountered this issue? Please provide more details.

I am using Mac OS 14.2 (23C64) and Flutter 3.22.2 in the Apple M3 system. The default example is that the keyboard cannot be used, and there are also issues with the above characters in Windows 11

**Comment by jlcool** [comment]
> > @SinyimZhi @hlwhl Can you help me take a look at this problem
> 
> Which platform you encountered this issue? Please provide more details.

My own project can input numbers and letters, but the delete key, directional key, select all shortcut key, and even mouse box selection are not allowed

**Comment by jlcool** [comment]
@hlwhl 辛苦哥们再给看下，为什么直接运行example也是无法使用键盘呢，鼠标框选也不行

**Comment by jlcool** [comment]
@SinyimZhi @hlwhl  我将CefWrapper.mm中processKeyboardEvent方法的!currentPlugin->_plugin->getAnyBrowserFocused()判断删除后键盘和鼠标就可以用了，就是鼠标选择的时候看起来没有选中状态，其他都没问题了

**Comment by SinyimZhi** [comment]
> @SinyimZhi @hlwhl 我将CefWrapper.mm中processKeyboardEvent方法的!currentPlugin->_plugin->getAnyBrowserFocused()判断删除后键盘和鼠标就可以用了，就是鼠标选择的时候看起来没有选中状态，其他都没问题了

macos的适配我可能近期暂时做不了了，现在手上没有mac设备。。mac的ime适配之前在flutter 3.16版本上0尝试做过，发现flutter的输入在macos上收不到回调，就没做下去了。

**Comment by jlcool** [comment]
> > @SinyimZhi @hlwhl 我将CefWrapper.mm中processKeyboardEvent方法的!currentPlugin->_plugin->getAnyBrowserFocused()判断删除后键盘和鼠标就可以用了，就是鼠标选择的时候看起来没有选中状态，其他都没问题了
> 
> macos的适配我可能近期暂时做不了了，现在手上没有mac设备。。mac的ime适配之前在flutter 3.16版本上0尝试做过，发现flutter的输入在macos上收不到回调，就没做下去了。

现在没有可用的mac版webview，就这个可以用一下，难啊😞

**Comment by hlwhl** [comment]
> > > @SinyimZhi @hlwhl 我将CefWrapper.mm中processKeyboardEvent方法的!currentPlugin->_plugin->getAnyBrowserFocused()判断删除后键盘和鼠标就可以用了，就是鼠标选择的时候看起来没有选中状态，其他都没问题了
> > 
> > 
> > macos的适配我可能近期暂时做不了了，现在手上没有mac设备。。mac的ime适配之前在flutter 3.16版本上0尝试做过，发现flutter的输入在macos上收不到回调，就没做下去了。
> 
> 现在没有可用的mac版webview，就这个可以用一下，难啊😞

只考虑macos的话可以看下官方插件的进度，处于一个基本可用的状态了 https://github.com/flutter/packages/pull/6221

**Comment by hlwhl** [comment]
> > > @SinyimZhi @hlwhl 我将CefWrapper.mm中processKeyboardEvent方法的!currentPlugin->_plugin->getAnyBrowserFocused()判断删除后键盘和鼠标就可以用了，就是鼠标选择的时候看起来没有选中状态，其他都没问题了
> > 
> > 
> > macos的适配我可能近期暂时做不了了，现在手上没有mac设备。。mac的ime适配之前在flutter 3.16版本上0尝试做过，发现flutter的输入在macos上收不到回调，就没做下去了。
> 
> 现在没有可用的mac版webview，就这个可以用一下，难啊😞

只考虑macos的话可以看下官方插件的进度，处于一个基本可用的状态了 https://github.com/flutter/packages/pull/6221

**Comment by jlcool** [comment]
> > > > @SinyimZhi @hlwhl 我将CefWrapper.mm中processKeyboardEvent方法的!currentPlugin->_plugin->getAnyBrowserFocused()判断删除后键盘和鼠标就可以用了，就是鼠标选择的时候看起来没有选中状态，其他都没问题了
> > > 
> > > 
> > > macos的适配我可能近期暂时做不了了，现在手上没有mac设备。。mac的ime适配之前在flutter 3.16版本上0尝试做过，发现flutter的输入在macos上收不到回调，就没做下去了。
> > 
> > 
> > 现在没有可用的mac版webview，就这个可以用一下，难啊😞
> 
> 只考虑macos的话可以看下官方插件的进度，处于一个基本可用的状态了 [flutter/packages#6221](https://github.com/flutter/packages/pull/6221)

官方的现在还不能用，有偿修复有没有兴趣了解下加v aliang-net
