### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by FutureHai** [hlwhl/webview_cef#71]
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:

    D:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.8.3+39993bd9d
    版权所有(C) Microsoft Corporation。保留所有权利。

    生成启动时间为 2023/6/23 16:39:14。
    节点 1 上的项目“D:\Main\Flutter\simple\webview_cef_simple\build\windows\CMakeFiles\3.18.20081302-MSVC_2\VCTargetsPath.vcxproj”(默认目标)。
    D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: 找不到 Windows SDK 版本 10.0.18362.0。请安装所需版本的 Windows SDK，或者在项目属性页中或通过右键单击解决方案并选择“重定解决方案目标”来更改 SDK 版本。 [D:\Main\Flutter\simple\webview_cef_simple\build\windows\CMakeFiles\3.18.20081302-MSVC_2\VCTargetsPath.vcxproj]
    已完成生成项目“D:\Main\Flutter\simple\webview_cef_simple\build\windows\CMakeFiles\3.18.20081302-MSVC_2\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “D:\Main\Flutter\simple\webview_cef_simple\build\windows\CMakeFiles\3.18.20081302-MSVC_2\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (_CheckWindowsSDKInstalled 目标) -> 
      D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: 找不到 Windows SDK 版本 10.0.18362.0。请安装所需版本的 Windows SDK，或者在项目属性页中或通过右键单击解决方案并选择“重定解决方案目标”来更改 SDK 版本。 [D:\Main\Flutter\simple\webview_cef_simple\build\windows\CMakeFiles\3.18.20081302-MSVC_2\VCTargetsPath.vcxproj]

        0 个警告
        1 个错误

    已用时间 00:00:10.01

  Exit code: 1

Exception: Unable to generate build files

VS2019中安装10.0.18362.0，安装完成后控制面板中显示的是10.0.18362.1，如下：
1）安装之前
![1](https://github.com/hlwhl/webview_cef/assets/48040056/0e785afd-2810-40ef-b213-1aca791f66f3)
2）安装10.0.18362.0
![5](https://github.com/hlwhl/webview_cef/assets/48040056/21678f3d-eda0-4d48-9ff7-aeca445a4c7c)
3）安装完成后
![4](https://github.com/hlwhl/webview_cef/assets/48040056/814d0d1c-86b2-4a8b-9520-1754a4cd7082)

**Comment by SinyimZhi** [comment]
@FutureHai 具体使用什么版本的windowsSDK编译取决于你电脑的环境变量，并不是由插件指定的。能确定下是否能运行起来flutter的示例项目吗？

**Comment by FutureHai** [comment]
报同样的错误
![image](https://github.com/hlwhl/webview_cef/assets/48040056/f92ad4f1-7baa-4e4c-af3a-f72aa186411a)

**Comment by FutureHai** [comment]
@SinyimZhi 报同样的错
![image](https://github.com/hlwhl/webview_cef/assets/48040056/5526b886-a634-4c24-ad0d-9d6ef41cccaf)

**Comment by SinyimZhi** [comment]
@FutureHai 这样的话就能确认该问题与本插件无关，我将关闭这个issue。你可以参考以下文档尝试解决这个问题https://zhuanlan.zhihu.com/p/496051774，或者在搜索引擎中搜索“找不到windowsSDK”来查找尝试其他解决方案。

**Comment by SinyimZhi** [comment]
@FutureHai 以上可以确定这个问题与本插件无关，我将关闭这个issue。你可以参考以下文档来解决这个问题，或者在搜索引擎中搜索“找不到windowsSDK”查询尝试其他解决方案。https://zhuanlan.zhihu.com/p/496051774

**Comment by FutureHai** [comment]
@SinyimZhi 非常感谢，确实是我系统的问题，修改UAP.props文件后成功！
