### ISSUE TITLE
Not able to set user agent

### ISSUE THREAD

**Issue by szwang1** [hlwhl/webview_cef#72]
Class cef_types has user_agent parameter, but it is returned value. 
How to set user agent?
Thank u.

**Comment by SinyimZhi** [comment]
@szwang1 CefSettings have a property user_agent, you can find CefSettings used in startCEF().
 I don't know do we really need a unified interface to set up the same user agent for all platforms @hlwhl

**Comment by hlwhl** [comment]
> @szwang1 CefSettings have a property user_agent, you can find CefSettings used in startCEF().
> 
>  I don't know do we really need a unified interface to set up the same user agent for all platforms @hlwhl 

Currently users can modify UA easily by making small changes to plugin code. So it’s a low priority feature.
We can provide unified settings like CEF in the future.

**Comment by SinyimZhi** [comment]
we afford a unified interface to allow developer set userAgent when cef initialized. but developers need to handle injecting different user agent parameters based on different operating systems themselves(except for some publicly available operating system information, CEF will obtain it on its own). @szwang1
