### ISSUE TITLE
[appstore upload ]Malformed Framework - The framework bundle   must contain a symbolic link

### ISSUE THREAD

**Issue by huafsud** [hlwhl/webview_cef#78]
NB的项目, 虽然体积大, 但是功能最NB, 

我也在尝试上传到appstore , 当我上传后, 提示我这些错误,  我不知道怎么改

求救大佬们 @SinyimZhi   @hlwhl , 感谢奉献这么厉害的项目 

```
ITMS-90291: Malformed Framework - The framework bundle (x.app/Contents/Frameworks/Chromium Embedded Framework.framework) must contain a symbolic link 'Chromium Embedded Framework' -> 'Versions/Current/Chromium Embedded Framework'. Refer to the Anatomy of Framework Bundles for more information.

ITMS-90291: Malformed Framework - The framework bundle (x.app/Contents/Frameworks/Chromium Embedded Framework.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information.

ITMS-90291: Malformed Framework - The framework bundle (x.app/Contents/Frameworks/Chromium Embedded Framework.framework) contains 'Libraries', which should be a symbolic link -> 'Versions/Current/Libraries'. Refer to the Anatomy of Framework Bundles for more information.

ITMS-90292: Malformed Framework - The framework bundle (x.app/Contents/Frameworks/Chromium Embedded Framework.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information.
```

**Comment by SinyimZhi** [comment]
@huafsud 我之前主要是win的技术栈，没有参与过AppStore上架流程，但是据我了解，cef本身有调用私有函数的情况，是不会被AppStore通过的，而且我们目前建设此插件的时候也没有使用cef的沙箱模式。参考[cef论坛](https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=16215&hilit=appstore&start=10) 另外，看你提供的错误信息，像是一些前置的问题。

**Comment by SinyimZhi** [comment]
有关这个问题，你试试寻求一下 @BullsEye34或者 @Mantresh Khurana 的帮助

**Comment by huafsud** [comment]
@SinyimZhi  感谢, 那估计上不了appstore了,   我考虑换个方案了.  再次感谢,

**Comment by jlcool** [comment]
弄半天无法上架😒，在readme里说明一下

**Comment by jlcool** [comment]
@huafsud 请问找到哪个可用的方案了吗？

**Comment by SinyimZhi** [comment]
> 弄半天无法上架😒，在readme里说明一下

我之前说不会被AppStore通过是指CEF官方编译版本，因为CEF官方没有任何关于保证遵守苹果相关政策的计划，但也不是完全不能上架，想要上架需要进行很多修改和尝试，不是完全做不到的。但因为苹果和谷歌的竞争，即使前期你的app上架了也不保证未来能够正常更新。参考https://magpcss.org/ceforum/viewtopic.php?f=10&t=16624、https://magpcss.org/ceforum/viewtopic.php?f=6&t=722、https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=16481。归根结底，应用上架涉及到太多因素，不是我们插件层所需要关心的问题。

**Comment by jlcool** [comment]
> > 弄半天无法上架😒，在readme里说明一下
> 
> 我之前说不会被AppStore通过是指CEF官方编译版本，因为CEF官方没有任何关于保证遵守苹果相关政策的计划，但也不是完全不能上架，想要上架需要进行很多修改和尝试，不是完全做不到的。但因为苹果和谷歌的竞争，即使前期你的app上架了也不保证未来能够正常更新。参考https://magpcss.org/ceforum/viewtopic.php?f=10&t=16624 https://magpcss.org/ceforum/viewtopic.php?f=6&t=722 [https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=16481。](https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=16481%E3%80%82) 归根结底，应用上架涉及到太多因素，不是我们插件层所需要关心的问题。

能力有限，无从下手
