### ISSUE TITLE
How to prohibit the display of this bullet box?

### ISSUE THREAD

**Issue by szxv587** [hlwhl/webview_cef#83]
![微信图片_20230817194958](https://github.com/hlwhl/webview_cef/assets/18606623/e0e1c74f-f722-40f2-b1af-45994c964cab)

**Comment by SinyimZhi** [comment]
@szxv587 sry,this box is for debug, we will delete these code soon. You can delete 2 lines after this [line](https://github.com/hlwhl/webview_cef/blob/823be8418a3320c7d8e0d02edbbb31dfb68d6e4c/common/webview_app.h#L35)  to disable it
