### ISSUE TITLE
Build error while compiling on MAC OS M1, 13.6(Ventura)

### ISSUE THREAD

**Issue by RakshithSarja** [hlwhl/webview_cef#86]
Hi @BullsEye34 @hlwhl  @SinyimZhi  ,
I am getting below error on MAC OS 13.6 (M1) when I tried to compile . I am not sure what exactly is the issue here. The same code works fine in windows .I am stuck on MAC. I have installed the necessary binaries as mentioned in pub.dev . Please let me know what could be the issue. Also there are lot of warnings in MAC ,is this expected or am I missing soemething? 
![image](https://github.com/hlwhl/webview_cef/assets/146819470/42a8d28f-c534-46b4-a67e-6c4b92a25881)

![image](https://github.com/hlwhl/webview_cef/assets/146819470/9529024b-3424-4b42-8015-dc9b22aaec06)

Thanks in advance.

**Comment by pradeepkarth** [comment]
@RakshithSarja I'm facing the same issue. How did you resolve it?

**Comment by RakshithSarja** [comment]
@pradeepkarth  I tried ths solution mentioned in the issue "error in macos Android Studio and temporary fix #27" .it should fix the  issue, give it a try
