### ISSUE TITLE
初始化加载时会一闪而过flutter官网的画面，然后再到设置的url画面

### ISSUE THREAD

**Issue by yanwzhang** [hlwhl/webview_cef#91]

**Comment by SinyimZhi** [comment]
@yanwzhang 是的webview_app[在init后立刻创建第一个browser](https://github.com/hlwhl/webview_cef/blob/580778ff0bbcd3115edf169b99460683ef2ece88/common/webview_app.cc#L90),是默认加载flutter官网。试试看这会如果加载空网址会不会出问题。

**Comment by SinyimZhi** [comment]
最新代码取消了native层的初始加载url @yanwzhang
