### ISSUE TITLE
Receiving Console Messages

### ISSUE THREAD

**Issue by bahricanyesil** [hlwhl/webview_cef#93]
How can I receive the console messages in the dart code (the ones printed as logs)? @SinyimZhi

**Comment by SinyimZhi** [comment]
sry,i didnt get your meant. can you put a screen shot show what messages you need? @bahricanyesil

**Comment by bahricanyesil** [comment]
I am asking for the corresponding way to listen console messages like we have "onConsoleMessage" parameter in the [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) package.

I want to trigger a function when an information from the console is received like the below message (you are already logging them).
<img width="1067" alt="Screenshot 2023-12-07 at 21 27 33" src="https://github.com/hlwhl/webview_cef/assets/60237280/966089fa-df5a-4275-a904-ecfb6858b244">

**Comment by bahricanyesil** [comment]
> sry,i didnt get your meant. can you put a screen shot show what messages you need? @bahricanyesil

I am asking for the corresponding way to listen console messages like we have "onConsoleMessage" parameter in the [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) package. @SinyimZhi 

I want to trigger a function when an information from the console is received like the below message (you are already logging them).
<img width="1067" alt="Screenshot 2023-12-07 at 21 27 33" src="https://github.com/hlwhl/webview_cef/assets/60237280/966089fa-df5a-4275-a904-ecfb6858b244">

**Comment by SinyimZhi** [comment]
> > sry,i didnt get your meant. can you put a screen shot show what messages you need? @bahricanyesil
> 
> I am asking for the corresponding way to listen console messages like we have "onConsoleMessage" parameter in the [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) package. @SinyimZhi
> 
> I want to trigger a function when an information from the console is received like the below message (you are already logging them). <img alt="Screenshot 2023-12-07 at 21 27 33" width="1067" src="https://private-user-images.githubusercontent.com/60237280/288884275-966089fa-df5a-4275-a904-ecfb6858b244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMjUyMDMsIm5iZiI6MTcwMjAyNDkwMywicGF0aCI6Ii82MDIzNzI4MC8yODg4ODQyNzUtOTY2MDg5ZmEtZGY1YS00Mjc1LWE5MDQtZWNmYjY4NThiMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA4NDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNWYxMjcyYzk5Y2QyM2IyN2E4NWU1NmY4NGRjMTI4ZjYyY2YzZmIwMjhiOTVjMTU4MTFjOWM1OTg0YTIzYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dmBejk_BO7iV4Ay6HJ2RJIycgzK2GdIX2KmIK83ernA">

@bahricanyesil I've checked inappwebview's doc, i recorgnized that you meant javascript console,right? Unfortunately, our project does not have this function on the CEF side right now.But I found there is a way  that can just use js code to realize. You can try  to excute these [codes](https://github.com/ianpgall/js-console-listener/blob/master/console-listener.js) and  use jschannel to trigger your function.

**Comment by alldev** [comment]
Feature of proper console processing is very high demand. Was upset to be unable to track JS console messages while I can definitely see them in console output. Probably this outputs come from deep inside CEF, I was unable to wrap them with runZoned (like [this way](https://stackoverflow.com/questions/66158432/how-to-listen-to-flutter-application-console-output)).

Hope this feature can be set to the top priority one.
Working with console is one of primary purposes of working with webview itself.

**Comment by SinyimZhi** [comment]
> Feature of proper console processing is very high demand. Was upset to be unable to track JS console messages while I can definitely see them in console output. Probably this outputs come from deep inside CEF, I was unable to wrap them with runZoned (like [this way](https://stackoverflow.com/questions/66158432/how-to-listen-to-flutter-application-console-output)).
> 
> Hope this feature can be set to the top priority one. Working with console is one of primary purposes of working with webview itself.

okay，i get it. I will check todo lists and work it in progress. @alldev @bahricanyesil

**Comment by alldev** [comment]
Many thanks, @SinyimZhi, we are looking forward to your further progress. The concept of reading console messages to track logs is way better than using Channels, which are too overengineered compared to the basic concept of logs.

**Comment by fufylev** [comment]
@SinyimZhi 
Hi there!
Looking forward to fixing this issue.
Would be very appreciated for the answer!

**Comment by SinyimZhi** [comment]
The newes version support get console messages from webview_event_listener @fufylev  @alldev @bahricanyesil
