### ISSUE TITLE
Dispose Callback Results with App Crash

### ISSUE THREAD

**Issue by bahricanyesil** [hlwhl/webview_cef#97]
When I call dispose on WebViewController, it directly closes the app. @SinyimZhi

**Comment by SinyimZhi** [comment]
I'm sorry, the dispose method called here is prepared for single instance mode，if you don't want close app immediately, you can remove [this](https://github.com/hlwhl/webview_cef/blob/a7b8bfb0dd3edba859d53ad5854fc556ff38ab50/lib/src/webview.dart#L95) line, and call it before close the app。

**Comment by bahricanyesil** [comment]
> I'm sorry, the dispose method called here is prepared for single instance mode，if you don't want close app immediately, you can remove [this](https://github.com/hlwhl/webview_cef/blob/a7b8bfb0dd3edba859d53ad5854fc556ff38ab50/lib/src/webview.dart#L95) line, and call it before close the app。

Thank you for the response. It was a bit confusing with the naming but I got it.
